import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MuiProviders } from "./providers/MuiProvider";
import { Params } from "./[[...slug]]/page";
import { config } from "../configs";
import { Layout } from "./context/LayoutContext";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Params>;
}>) {
  const resolvedParams = await params;
  const slug = resolvedParams.slug || [];
  const path = slug ? `/${slug.join('/')}` : '/';
  const pageConfig = config[path];

  console.log('%capp/layout.tsx:36 pageConfig', 'color: #007acc;', pageConfig);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <Layout initialConfig={pageConfig}>
            <MuiProviders>
              {children}
            </MuiProviders>
            </Layout>
        </ClerkProvider>
      </body>
    </html>
  );
}
